from . import sale_quot
from . import sale_quot_line
from . import sale_order
from . import sale_order_line
from . import report_sale
from . import sale_stage
from . import sale_opportunity
from . import sale_lead
from . import lead_source
from . import convert_lead
from . import sale_target
from . import sale_coupon
from . import competitor
from . import opport_compet
from . import report_sale_profit
from . import report_sale_profit_details
from . import sale_cost
from . import quot_cost
from . import report_unpaid_sale
from . import report_sale_payment
from . import sale_forecast
from . import sale_forecast_line
from . import sale_channel
from . import sale_promotion
from . import sale_coupon_master
from . import sale_coupon
from . import sale_order_promotion
from . import account_payment
from . import stock_picking
from . import sale_event
from . import seller
from . import sale_return
from . import sale_return_line
from . import payment_method
from . import sale_voucher
from . import sale_categ
from . import opport_to_quot
from . import sale_recurring
from . import email_message
from . import sale_modif
from . import report_sale_commission
from . import delivery_term
from . import seller_commission
from . import gen_sale_report
from . import sale_activ
