from . import shopee_account
from . import sync_record
from . import product
#from . import product_categ
#from . import product_brand
from . import ship_method
from . import sale_order
from . import contact
from . import product_shopee_details
from . import shopee_settings
from . import stock_picking
from . import shopee_order
from . import shopee_order_item
from . import shopee_webhook
from . import stock_move
from . import shopee_product
from . import shopee_product_categ
from . import shopee_product_variation
from . import shopee_product_variation_option
from . import shopee_product_model
